#remote_theme: pages-themes/cayman@v0.2.0
remote_theme: "jekyll/minima@1e8a445"
title: CrUISE-AC
#description: [A short description of your site's purpose]
show_downloads: false
google_analytics: G-KN2XPMJ0JH